# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.06.16

minecraft_version=1.20.6
minecraft_version_range=[1.20.4,1.21)
neo_version=20.6.125
neo_version_range=[20.6,)
loader_version_range=[2,)

mod_version=3.0.1+1.20.6neoforge
mod_group_id=com.kingcontaria
mod_id=fastquit
mod_name=Fastquit
mod_license=MIT
mod_authors=KingContaria, Kaleb Langley
mod_description=This mod lets you return to the Title Screen early while your world is still saving in the background.

cloth_config_version=14.0.139
