# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mapping_channel=official
mapping_version=1.16.5

minecraft_version=1.16.5
minecraft_version_range=[1.16,1.17)
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)

# Mod Properties
mod_version=3.0.1+1.16.5forge
mod_group_id=com.kingcontaria
mod_id=fastquit
mod_name=Fastquit
mod_license=MIT
mod_authors=KingContaria, Kaleb Langley
mod_description=This mod lets you return to the Title Screen early while your world is still saving in the background.

# Dependencies
cloth_config_version=4.17.101
mixinextras_version=0.3.6
