modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "fastquit"
logoFile = "icon.png"
version = "3.0.1+1.20.1forge"
displayName = "FastQuit"
description = "This mod lets you return to the Title Screen early while your world is still saving in the background."
authors = "KingContaria, Kaleb Langley"
[[dependencies.fastquit]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fastquit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fastquit]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.136,)"
ordering="NONE"
side="BOTH"
