modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
logoFile = "icon.png"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "${mod_authors}"
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId="cloth_config"
mandatory=true
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="BOTH"
